# Generated by Django 4.2.6 on 2023-10-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_likes_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated_by',
            field=models.DateTimeField(),
        )
    ]
